// <auto-generated />
using System;
using AutoHubProjeto.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoHubProjeto.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251130202016_AddFavoritos")]
    partial class AddFavoritos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoHubProjeto.Models.Administrador", b =>
                {
                    b.Property<int>("IdAdmin")
                        .HasColumnType("int");

                    b.HasKey("IdAdmin")
                        .HasName("PK__Administ__4C3F97F471DF33AB");

                    b.ToTable("Administrador", (string)null);
                });

            modelBuilder.Entity("AutoHubProjeto.Models.Anuncio", b =>
                {
                    b.Property<int>("IdAnuncio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnuncio"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("DataPublicacao")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("ativo");

                    b.Property<int>("IdVeiculo")
                        .HasColumnType("int");

                    b.Property<int>("IdVendedor")
                        .HasColumnType("int");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdAnuncio")
                        .HasName("PK__Anuncio__BD6A7622F40512F1");

                    b.HasIndex("IdVendedor");

                    b.HasIndex(new[] { "IdVeiculo" }, "UQ__Anuncio__CAC4F347BC1C1231")
                        .IsUnique();

                    b.ToTable("Anuncio", (string)null);
                });

            modelBuilder.Entity("AutoHubProjeto.Models.AnuncioImagem", b =>
                {
                    b.Property<int>("IdImagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImagem"));

                    b.Property<int>("IdAnuncio")
                        .HasColumnType("int");

                    b.Property<int?>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("IdImagem")
                        .HasName("PK__AnuncioI__B42D8F15C1B3A80F");

                    b.HasIndex("IdAnuncio");

                    b.ToTable("AnuncioImagem", (string)null);
                });

            modelBuilder.Entity("AutoHubProjeto.Models.Compra", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompra"));

                    b.Property<DateTime>("DataCompra")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("EstadoPagamento")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("pendente");

                    b.Property<int>("IdAnuncio")
                        .HasColumnType("int");

                    b.Property<int>("IdComprador")
                        .HasColumnType("int");

                    b.Property<string>("ReferenciaPagamento")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(12, 2)");

                    b.HasKey("IdCompra")
                        .HasName("PK__Compra__0A5CDB5CC3F0906D");

                    b.HasIndex("IdAnuncio");

                    b.HasIndex("IdComprador");

                    b.ToTable("Compra", (string)null);
                });

            modelBuilder.Entity("AutoHubProjeto.Models.Comprador", b =>
                {
                    b.Property<int>("IdComprador")
                        .HasColumnType("int");

                    b.Property<string>("FiltroFavorito")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("MarcaFavorita")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("NotificacoesAtivas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("IdComprador")
                        .HasName("PK__Comprado__324FC82048A45058");

                    b.ToTable("Comprador", (string)null);
                });

            modelBuilder.Entity("AutoHubProjeto.Models.LogAdministrativo", b =>
                {
                    b.Property<long>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdLog"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("DataHora")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Detalhes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Entidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdAdmin")
                        .HasColumnType("int");

                    b.Property<string>("IdEntidade")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("IdLog")
                        .HasName("PK__LogAdmin__0C54DBC6A81E41B3");

                    b.HasIndex("IdAdmin");

                    b.ToTable("LogAdministrativo", (string)null);
                });

            modelBuilder.Entity("AutoHubProjeto.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<DateTime>("DataReserva")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("ativada");

                    b.Property<DateTime>("ExpiraEm")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("IdAnuncio")
                        .HasColumnType("int");

                    b.Property<int>("IdComprador")
                        .HasColumnType("int");

                    b.HasKey("IdReserva")
                        .HasName("PK__Reserva__0E49C69D8A6D5410");

                    b.HasIndex("IdAnuncio");

                    b.HasIndex("IdComprador");

                    b.ToTable("Reserva", (string)null);
                });

            modelBuilder.Entity("AutoHubProjeto.Models.Utilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoConfirmacao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmado")
                        .HasColumnType("bit");

                    b.Property<string>("EstadoConta")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("ativo");

                    b.Property<string>("Morada")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varbinary(128)");

                    b.Property<string>("ResetPasswordCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Utilizad__3214EC07E93A86E5");

                    b.HasIndex(new[] { "Email" }, "UQ_Utilizador_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "UQ_Utilizador_Username")
                        .IsUnique();

                    b.ToTable("Utilizador", (string)null);
                });

            modelBuilder.Entity("AutoHubProjeto.Models.Veiculo", b =>
                {
                    b.Property<int>("IdVeiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVeiculo"));

                    b.Property<short>("Ano")
                        .HasColumnType("smallint");

                    b.Property<string>("Caixa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Combustivel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("PrecoSugerido")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int>("Quilometragem")
                        .HasColumnType("int");

                    b.HasKey("IdVeiculo")
                        .HasName("PK__Veiculo__CAC4F346239F6C57");

                    b.ToTable("Veiculo", (string)null);
                });

            modelBuilder.Entity("AutoHubProjeto.Models.Vendedor", b =>
                {
                    b.Property<int>("IdVendedor")
                        .HasColumnType("int");

                    b.Property<bool>("Aprovado")
                        .HasColumnType("bit");

                    b.Property<string>("DadosFaturacao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("IdAdminAprovador")
                        .HasColumnType("int");

                    b.Property<string>("Nif")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("NIF");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.HasKey("IdVendedor")
                        .HasName("PK__Vendedor__16D6C7CA033831D8");

                    b.HasIndex("IdAdminAprovador");

                    b.HasIndex(new[] { "Nif" }, "UQ_Vendedor_NIF")
                        .IsUnique();

                    b.ToTable("Vendedor", (string)null);
                });

            modelBuilder.Entity("AutoHubProjeto.Models.Visitum", b =>
                {
                    b.Property<int>("IdVisita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVisita"));

                    b.Property<DateTime>("DataHora")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("marcada");

                    b.Property<int>("IdAnuncio")
                        .HasColumnType("int");

                    b.Property<int>("IdComprador")
                        .HasColumnType("int");

                    b.HasKey("IdVisita")
                        .HasName("PK__Visita__020AC8276F4BA839");

                    b.HasIndex("IdAnuncio");

                    b.HasIndex("IdComprador");

                    b.ToTable("Visita");
                });

            modelBuilder.Entity("Favorito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataFavorito")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAnuncio")
                        .HasColumnType("int");

                    b.Property<int>("IdComprador")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAnuncio");

                    b.HasIndex("IdComprador");

                    b.ToTable("Favorito", (string)null);
                });

            modelBuilder.Entity("AutoHubProjeto.Models.Administrador", b =>
                {
                    b.HasOne("AutoHubProjeto.Models.Utilizador", "IdAdminNavigation")
                        .WithOne("Administrador")
                        .HasForeignKey("AutoHubProjeto.Models.Administrador", "IdAdmin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Administr__IdAdm__3E52440B");

                    b.Navigation("IdAdminNavigation");
                });

            modelBuilder.Entity("AutoHubProjeto.Models.Anuncio", b =>
                {
                    b.HasOne("AutoHubProjeto.Models.Veiculo", "IdVeiculoNavigation")
                        .WithOne("Anuncio")
                        .HasForeignKey("AutoHubProjeto.Models.Anuncio", "IdVeiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Anuncio__IdVeicu__5629CD9C");

                    b.HasOne("AutoHubProjeto.Models.Vendedor", "IdVendedorNavigation")
                        .WithMany("Anuncios")
                        .HasForeignKey("IdVendedor")
                        .IsRequired()
                        .HasConstraintName("FK__Anuncio__IdVende__5535A963");

                    b.Navigation("IdVeiculoNavigation");

                    b.Navigation("IdVendedorNavigation");
                });

            modelBuilder.Entity("AutoHubProjeto.Models.AnuncioImagem", b =>
                {
                    b.HasOne("AutoHubProjeto.Models.Anuncio", "IdAnuncioNavigation")
                        .WithMany("AnuncioImagems")
                        .HasForeignKey("IdAnuncio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__AnuncioIm__IdAnu__5CD6CB2B");

                    b.Navigation("IdAnuncioNavigation");
                });

            modelBuilder.Entity("AutoHubProjeto.Models.Compra", b =>
                {
                    b.HasOne("AutoHubProjeto.Models.Anuncio", "IdAnuncioNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("IdAnuncio")
                        .IsRequired()
                        .HasConstraintName("FK__Compra__IdAnunci__60A75C0F");

                    b.HasOne("AutoHubProjeto.Models.Comprador", "IdCompradorNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("IdComprador")
                        .IsRequired()
                        .HasConstraintName("FK__Compra__IdCompra__5FB337D6");

                    b.Navigation("IdAnuncioNavigation");

                    b.Navigation("IdCompradorNavigation");
                });

            modelBuilder.Entity("AutoHubProjeto.Models.Comprador", b =>
                {
                    b.HasOne("AutoHubProjeto.Models.Utilizador", "IdCompradorNavigation")
                        .WithOne("Comprador")
                        .HasForeignKey("AutoHubProjeto.Models.Comprador", "IdComprador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Comprador__IdCom__47DBAE45");

                    b.Navigation("IdCompradorNavigation");
                });

            modelBuilder.Entity("AutoHubProjeto.Models.LogAdministrativo", b =>
                {
                    b.HasOne("AutoHubProjeto.Models.Administrador", "IdAdminNavigation")
                        .WithMany("LogAdministrativos")
                        .HasForeignKey("IdAdmin")
                        .IsRequired()
                        .HasConstraintName("FK__LogAdmini__IdAdm__4BAC3F29");

                    b.Navigation("IdAdminNavigation");
                });

            modelBuilder.Entity("AutoHubProjeto.Models.Reserva", b =>
                {
                    b.HasOne("AutoHubProjeto.Models.Anuncio", "IdAnuncioNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdAnuncio")
                        .IsRequired()
                        .HasConstraintName("FK__Reserva__IdAnunc__68487DD7");

                    b.HasOne("AutoHubProjeto.Models.Comprador", "IdCompradorNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdComprador")
                        .IsRequired()
                        .HasConstraintName("FK__Reserva__IdCompr__6754599E");

                    b.Navigation("IdAnuncioNavigation");

                    b.Navigation("IdCompradorNavigation");
                });

            modelBuilder.Entity("AutoHubProjeto.Models.Vendedor", b =>
                {
                    b.HasOne("AutoHubProjeto.Models.Administrador", "IdAdminAprovadorNavigation")
                        .WithMany("Vendedors")
                        .HasForeignKey("IdAdminAprovador")
                        .HasConstraintName("FK__Vendedor__IdAdmi__440B1D61");

                    b.HasOne("AutoHubProjeto.Models.Utilizador", "IdVendedorNavigation")
                        .WithOne("Vendedor")
                        .HasForeignKey("AutoHubProjeto.Models.Vendedor", "IdVendedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Vendedor__IdVend__4222D4EF");

                    b.Navigation("IdAdminAprovadorNavigation");

                    b.Navigation("IdVendedorNavigation");
                });

            modelBuilder.Entity("AutoHubProjeto.Models.Visitum", b =>
                {
                    b.HasOne("AutoHubProjeto.Models.Anuncio", "IdAnuncioNavigation")
                        .WithMany("Visita")
                        .HasForeignKey("IdAnuncio")
                        .IsRequired()
                        .HasConstraintName("FK__Visita__IdAnunci__6EF57B66");

                    b.HasOne("AutoHubProjeto.Models.Comprador", "IdCompradorNavigation")
                        .WithMany("Visita")
                        .HasForeignKey("IdComprador")
                        .IsRequired()
                        .HasConstraintName("FK__Visita__IdCompra__6E01572D");

                    b.Navigation("IdAnuncioNavigation");

                    b.Navigation("IdCompradorNavigation");
                });

            modelBuilder.Entity("Favorito", b =>
                {
                    b.HasOne("AutoHubProjeto.Models.Anuncio", "Anuncio")
                        .WithMany()
                        .HasForeignKey("IdAnuncio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoHubProjeto.Models.Comprador", "Comprador")
                        .WithMany()
                        .HasForeignKey("IdComprador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anuncio");

                    b.Navigation("Comprador");
                });

            modelBuilder.Entity("AutoHubProjeto.Models.Administrador", b =>
                {
                    b.Navigation("LogAdministrativos");

                    b.Navigation("Vendedors");
                });

            modelBuilder.Entity("AutoHubProjeto.Models.Anuncio", b =>
                {
                    b.Navigation("AnuncioImagems");

                    b.Navigation("Compras");

                    b.Navigation("Reservas");

                    b.Navigation("Visita");
                });

            modelBuilder.Entity("AutoHubProjeto.Models.Comprador", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("Reservas");

                    b.Navigation("Visita");
                });

            modelBuilder.Entity("AutoHubProjeto.Models.Utilizador", b =>
                {
                    b.Navigation("Administrador");

                    b.Navigation("Comprador");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("AutoHubProjeto.Models.Veiculo", b =>
                {
                    b.Navigation("Anuncio");
                });

            modelBuilder.Entity("AutoHubProjeto.Models.Vendedor", b =>
                {
                    b.Navigation("Anuncios");
                });
#pragma warning restore 612, 618
        }
    }
}
